Repository PopFri/BackEnd, pull requests merged in 2025-04, with the labels that each got.

#2 [FEAT] #1 초기 파일 설정 및 응답 통일
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/popfri/spring/Application.java
  src/main/java/popfri/spring/apiPayload/ApiResponse.java
  src/main/java/popfri/spring/apiPayload/code/BaseCode.java
  src/main/java/popfri/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/popfri/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/popfri/spring/apiPayload/code/ReasonDTO.java
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/popfri/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/popfri/spring/apiPayload/exception/GeneralException.java
  src/main/java/popfri/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/popfri/spring/converter/TempConverter.java
  src/main/java/popfri/spring/domain/Temp.java
  src/main/java/popfri/spring/domain/common/BaseEntity.java
  src/main/java/popfri/spring/repository/TempRepository.java
  src/main/java/popfri/spring/service/TempService/TempCommandService.java
  src/main/java/popfri/spring/service/TempService/TempQueryService.java
  src/main/java/popfri/spring/web/controller/TempRestController.java
  src/main/java/popfri/spring/web/dto/TempRequest.java
  src/main/java/popfri/spring/web/dto/TempResponse.java
  src/main/resources/application.yml
  src/test/java/popfri/spring/ApplicationTests.java
Labels: :sparkles: feature

#4 [FEAT] #3 Swagger 설정
  build.gradle
  src/main/java/popfri/spring/apiPayload/ApiResponse.java
  src/main/java/popfri/spring/config/SwaggerConfig.java
  src/main/java/popfri/spring/web/controller/TempRestController.java
  src/main/java/popfri/spring/web/dto/TempResponse.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#6 [FEAT] #5 구글 로그인 구현
  build.gradle
  src/main/java/popfri/spring/OAuth2/dto/CustomOAuth2User.java
  src/main/java/popfri/spring/OAuth2/dto/GoogleResponse.java
  src/main/java/popfri/spring/OAuth2/dto/OAuth2Response.java
  src/main/java/popfri/spring/OAuth2/dto/UserDTO.java
  src/main/java/popfri/spring/OAuth2/handler/CustomSuccessHandler.java
  src/main/java/popfri/spring/OAuth2/service/CustomOAuth2UserService.java
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/config/CorsMvcConfig.java
  src/main/java/popfri/spring/config/SecurityConfig.java
  src/main/java/popfri/spring/domain/User.java
  src/main/java/popfri/spring/jwt/JWTFilter.java
  src/main/java/popfri/spring/jwt/JWTUtil.java
  src/main/java/popfri/spring/repository/UserRepository.java
  src/main/java/popfri/spring/web/controller/UserController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#8 [FEAT] #7 naver 로그인
  src/main/java/popfri/spring/OAuth2/dto/NaverResponse.java
  src/main/java/popfri/spring/OAuth2/service/CustomOAuth2UserService.java
  src/main/java/popfri/spring/config/SecurityConfig.java
Labels: :sparkles: feature

#10 [FEAT] #9 kakao 로그인
  src/main/java/popfri/spring/OAuth2/dto/KakaoResponse.java
  src/main/java/popfri/spring/OAuth2/service/CustomOAuth2UserService.java
  src/main/java/popfri/spring/domain/User.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#12 [FEAT] #11 유저 정보 조회
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/apiPayload/exception/handler/UserHandler.java
  src/main/java/popfri/spring/converter/TempConverter.java
  src/main/java/popfri/spring/converter/UserConverter.java
  src/main/java/popfri/spring/domain/Temp.java
  src/main/java/popfri/spring/jwt/CookieUtil.java
  src/main/java/popfri/spring/repository/TempRepository.java
  src/main/java/popfri/spring/service/TempService/TempCommandService.java
  src/main/java/popfri/spring/service/TempService/TempQueryService.java
  src/main/java/popfri/spring/service/UserService.java
  src/main/java/popfri/spring/web/controller/TempRestController.java
  src/main/java/popfri/spring/web/controller/UserController.java
  src/main/java/popfri/spring/web/dto/TempResponse.java
  src/main/java/popfri/spring/web/dto/UserRequest.java
  src/main/java/popfri/spring/web/dto/UserResponse.java
Labels: :sparkles: feature

#14 [FIX] #13 JWT 관련 오류 수정
  src/main/java/popfri/spring/OAuth2/handler/CustomSuccessHandler.java
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/config/SecurityConfig.java
  src/main/java/popfri/spring/jwt/JWTFilter.java
  src/main/java/popfri/spring/jwt/JWTUtil.java
Labels: :bug: bugfix

#16 [FEAT] #15 영화 상세 정보 조회
  .gitignore
  build.gradle
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/apiPayload/exception/handler/MovieHandler.java
  src/main/java/popfri/spring/config/SecurityConfig.java
  src/main/java/popfri/spring/service/MovieService.java
  src/main/java/popfri/spring/web/controller/MovieController.java
  src/main/java/popfri/spring/web/dto/MovieResponse.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#19 [FEAT] #18 상황별 영화 추천
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/domain/RecHistory.java
  src/main/java/popfri/spring/domain/User.java
  src/main/java/popfri/spring/domain/enums/RecType.java
  src/main/java/popfri/spring/repository/RecHistoryRepository.java
  src/main/java/popfri/spring/service/HistoryService.java
  src/main/java/popfri/spring/service/MovieService.java
  src/main/java/popfri/spring/web/controller/MovieController.java
  src/main/java/popfri/spring/web/dto/GPTRequest.java
  src/main/java/popfri/spring/web/dto/GPTResponse.java
  src/main/java/popfri/spring/web/dto/MovieResponse.java
Labels: :sparkles: feature

#21 [FEAT] #20 시간별 영화 추천
  src/main/java/popfri/spring/service/HistoryService.java
  src/main/java/popfri/spring/service/MovieService.java
  src/main/java/popfri/spring/web/controller/MovieController.java
Labels: :sparkles: feature

#23 [FEAT] #17 리뷰 작성 및 조회 기능
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/apiPayload/exception/handler/ReviewHandler.java
  src/main/java/popfri/spring/domain/DislikeReview.java
  src/main/java/popfri/spring/domain/LikeReview.java
  src/main/java/popfri/spring/domain/Review.java
  src/main/java/popfri/spring/domain/User.java
  src/main/java/popfri/spring/repository/DislikeReviewRepository.java
  src/main/java/popfri/spring/repository/LikeReviewRepository.java
  src/main/java/popfri/spring/repository/ReviewRepository.java
  src/main/java/popfri/spring/repository/UserRepository.java
  src/main/java/popfri/spring/service/MovieService.java
  src/main/java/popfri/spring/service/ReviewService.java
  src/main/java/popfri/spring/service/UserService.java
  src/main/java/popfri/spring/web/controller/ReviewController.java
  src/main/java/popfri/spring/web/controller/UserController.java
  src/main/java/popfri/spring/web/dto/ReviewResponse.java
  src/test/java/popfri/spring/service/ReviewServiceTest.java
Labels: :sparkles: feature

#26 [FEAT] #22 유저 추천 기록 조회
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/apiPayload/exception/handler/HistoryHandler.java
  src/main/java/popfri/spring/converter/HistoryConverter.java
  src/main/java/popfri/spring/repository/RecHistoryRepository.java
  src/main/java/popfri/spring/service/HistoryService.java
  src/main/java/popfri/spring/web/controller/UserController.java
  src/main/java/popfri/spring/web/dto/HistoryResponse.java
Labels: :sparkles: feature

#28 [FEAT] #27 유저 방문 기록 저장
  src/main/java/popfri/spring/domain/VisitHistory.java
  src/main/java/popfri/spring/repository/VisitHistoryRepository.java
  src/main/java/popfri/spring/service/HistoryService.java
  src/main/java/popfri/spring/web/controller/UserController.java
  src/main/java/popfri/spring/web/dto/HistoryRequest.java
Labels: :sparkles: feature

#29 [FEAT] #25 박스오피스 순위 반환 기능 구현
  build.gradle
  src/main/java/popfri/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/popfri/spring/service/MovieService.java
  src/main/java/popfri/spring/service/ReviewService.java
  src/main/java/popfri/spring/web/controller/MovieController.java
  src/main/java/popfri/spring/web/dto/MovieResponse.java
Labels: :sparkles: feature

#32 [REFACTOR] #31 리뷰 관련 로직 수정
  src/main/java/popfri/spring/domain/enums/ReviewActionType.java
  src/main/java/popfri/spring/service/ReviewService.java
  src/main/java/popfri/spring/web/controller/ReviewController.java
  src/test/java/popfri/spring/service/ReviewServiceTest.java
Labels: :recycle: refactor
