Repository PopFri/BackEnd, pull requests merged in 2025-06, with the labels that each got.

#49 [FEAT] #48 로그아웃 기능 구현
  src/main/java/popfri/spring/domain/User.java
  src/main/java/popfri/spring/jwt/CookieUtil.java
  src/main/java/popfri/spring/web/controller/UserController.java
Labels: :bug: bugfix, :sparkles: feature

#51 [FEAT] #50 유저 성별, 나이 조회 구현
  src/main/java/popfri/spring/OAuth2/handler/CustomSuccessHandler.java
  src/main/java/popfri/spring/converter/UserConverter.java
  src/main/java/popfri/spring/web/controller/UserController.java
  src/main/java/popfri/spring/web/dto/UserResponse.java
Labels: :sparkles: feature, :recycle: refactor

#53 [FEAT] #52 유저 provide_id 반환 컨트롤러 작성
  dockerfile
  src/main/java/popfri/spring/web/controller/UserController.java
Labels: :sparkles: feature

#55 [FEAT] #53 성별, 나이 별 선호영화 데이터 반환
  src/main/java/popfri/spring/config/SecurityConfig.java
  src/main/java/popfri/spring/jwt/JWTFilter.java
  src/main/java/popfri/spring/repository/VisitHistoryRepository.java
  src/main/java/popfri/spring/service/HistoryService.java
  src/main/java/popfri/spring/sse/SseController.java
  src/main/java/popfri/spring/sse/SseEmitters.java
  src/main/java/popfri/spring/web/dto/HistoryResponse.java
Labels: :sparkles: feature

#57 [FEAT] #56 성별, 나이 별 추천 영화 데이터 반환
  src/main/java/popfri/spring/repository/RecHistoryRepository.java
  src/main/java/popfri/spring/service/HistoryService.java
  src/main/java/popfri/spring/sse/SseController.java
  src/main/java/popfri/spring/sse/SseEmitters.java
Labels: :sparkles: feature, :recycle: refactor

#63 [FEAT] #61 성별, 나이 통합 방문 데이터 반환
  src/main/java/popfri/spring/repository/VisitHistoryRepository.java
  src/main/java/popfri/spring/service/MovieService.java
  src/main/java/popfri/spring/sse/SseController.java
  src/main/java/popfri/spring/sse/SseEmitters.java
Labels: :sparkles: feature
